// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: common.proto

/* eslint-disable */
import { ErrorCode } from "./enums";

export const protobufPackage = "common";

export interface User {
  userId: number;
  email: string;
  name: string;
  role: string;
  isActive: boolean;
  lastLoginAt: string;
  emailVerified: boolean;
  payCount: number;
  pbxExtension?: number | undefined;
}

export interface Error {
  message?: string | undefined;
  errorCode?: ErrorCode | undefined;
}

export const COMMON_PACKAGE_NAME = "common";
