// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: enums.proto

/* eslint-disable */

export const protobufPackage = "enums";

export enum UserRole {
  /** USER_ROLE_UNSPECIFIED - обязательное значение по умолчанию в proto3 */
  USER_ROLE_UNSPECIFIED = 0,
  USER = 1,
  ADMIN = 2,
  UNRECOGNIZED = -1,
}

export enum ErrorCode {
  /** ERROR_CODE_UNSPECIFIED - No error */
  ERROR_CODE_UNSPECIFIED = 0,
  /** INVALID_INPUT - Validation errors (400) */
  INVALID_INPUT = 1000,
  INVALID_EMAIL_FORMAT = 1001,
  INVALID_PASSWORD_FORMAT = 1002,
  PASSWORD_TOO_SHORT = 1003,
  MISSING_REQUIRED_FIELD = 1004,
  /** INVALID_CREDENTIALS - Authentication errors (401) */
  INVALID_CREDENTIALS = 2000,
  INVALID_TOKEN = 2001,
  TOKEN_EXPIRED = 2002,
  /** USER_NOT_ACTIVE - Authorization errors (403) */
  USER_NOT_ACTIVE = 3000,
  EMAIL_NOT_VERIFIED = 3001,
  INSUFFICIENT_PERMISSIONS = 3002,
  /** USER_NOT_FOUND - Resource errors (404/409) */
  USER_NOT_FOUND = 4000,
  USER_ALREADY_EXISTS = 4001,
  REFRESH_TOKEN_NOT_FOUND = 4002,
  /** INTERNAL_ERROR - Server errors (500) */
  INTERNAL_ERROR = 5000,
  DATABASE_ERROR = 5001,
  HASH_ERROR = 5002,
  UNRECOGNIZED = -1,
}

export const ENUMS_PACKAGE_NAME = "enums";
